#!/bin/sh

# gitolite VREF to check code ownership

# see gitolite docs for what the first 7 arguments mean

# exit status:
#   always 0

# TODO (kevin): Is this necessary?
# die() { echo "$@" >&2; exit 1; }
# [ -z "$8" ] && die "not meant to be run manually"

ref=${1}
oldsha=${2}
newsha=${3}
branch=${8}

export PYTHONPATH=${GL_BINDIR}/lib/site-packages
python -m fsqa.ownership ${ref} ${oldsha} ${newsha} ${PWD} ${branch}

exit 0
