#!/bin/sh

# gitolite VREF to check that a peer has reviewed the code

# see gitolite docs for what the first 7 arguments mean

# exit status:
#   always 0

# TODO what to do here?
# die() { echo "$@" >&2; exit 1; }
# [ -z "$8" ] && die "not meant to be run manually"

oldsha=$2
newsha=$3

PYTHONPATH=$GL_BINDIR/lib/site-packages
python -m fsqa.peer $oldsha $newsha $PWD

exit 0
