#!/bin/sh

# gitolite VREF to check code reviewed by someone with readability

# see gitolite docs for what the first 7 arguments mean

# exit status:
#   always 0

# TODO (kevin): Is this necessary?
# die() { echo "$@" >&2; exit 1; }
# [ -z "$8" ] && die "not meant to be run manually"

oldsha=${2}
newsha=${3}

export PYTHONPATH=${GL_BINDIR}/lib/site-packages
python -m fsqa.readability.__init__ ${oldsha} ${newsha} ${PWD}

exit 0
